[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:auth]
directory=/app/auth-service
command=node src/index.js
environment=PORT="3020",CORE_SERVICE_URL="http://127.0.0.1:3022"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:workday]
directory=/app/workday-service
command=node src/index.js
environment=PORT="3021",CORE_SERVICE_URL="http://127.0.0.1:3022",CORE_SERVICE_HOSTPORT="127.0.0.1:3022"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

[program:core]
directory=/app/core-service
command=node src/index.js
environment=PORT="3022",WORKDAY_SERVICE_URL="http://127.0.0.1:3021",WORKDAY_SERVICE_HOSTPORT="127.0.0.1:3021"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

[program:report]
directory=/app/report-service
command=node src/index.js
environment=PORT="3023",AUTH_SERVICE_URL="http://127.0.0.1:3020",AUTH_SERVICE_HOSTPORT="127.0.0.1:3020",WORKDAY_SERVICE_URL="http://127.0.0.1:3021",WORKDAY_SERVICE_HOSTPORT="127.0.0.1:3021",CORE_SERVICE_URL="http://127.0.0.1:3022",CORE_SERVICE_HOSTPORT="127.0.0.1:3022"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=30

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=90
